language: node_js
node_js:
  - "6.9"

branches:
  only:
    - deploy
    
before_script:
  - cd cleint
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - npm install

script:
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

before_install:
  - cd ..
  - cd server
  - openssl aes-256-cbc -k "$enc_pass" -in super_secret.txt.enc -out foodMe-046bd9fd6e24.json -d
  
install: 
  - npm install
deploy:
  provider: gae
  keyfile: "foodMe-046bd9fd6e24.json"
  project: "foodme-199118"
  on:
    all_branches: true
  provider: firebase
  token:
    secure: "YOUR ENCRYPTED token"
  project: "myapp-staging"

notifications:
  email:
    on_failure: change
    on_success: change